name: Deploy static content to Pages

on:
  # Run on all pushes to main
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run on pull requests to main
  pull_request:
    # Note that this specifies the target branch, not the branch that the PR is from
    branches:
      - main

jobs:
  pages:
    uses: XaverianTeamRobotics/github-pages-deployment-action/.github/workflows/pages.yml@main
    with:
      cloudflare-pages-project-name: xbhs-robotics-docs
    secrets: inherit
